//! Artifact, region, ownership, and role-safe image records.

use std::marker::PhantomData;

use sim_kernel::Datum;

use crate::{
    ArtifactId, BaseImageId, DisclosureDecisionId, FacetError, FacetId, FacetSemanticId, ImageId,
    IntendedImageId, MergePolicyId, ObservedImageId, OwnerId, PostimageId, ProjectionId, RegionId,
    field, number,
};

/// Portable whole-file presence, bytes, and Unix permission bits.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PortableImage {
    /// Exact bytes; `None` means the path is absent.
    pub bytes: Option<Vec<u8>>,
    /// Portable permission bits; present exactly when bytes are present.
    pub mode: Option<u32>,
}

impl PortableImage {
    /// Constructs an absent image.
    pub const fn absent() -> Self {
        Self {
            bytes: None,
            mode: None,
        }
    }

    /// Constructs a present image and validates its portable mode.
    pub fn file(bytes: impl Into<Vec<u8>>, mode: u32) -> Result<Self, FacetError> {
        let value = Self {
            bytes: Some(bytes.into()),
            mode: Some(mode),
        };
        value.validate()?;
        Ok(value)
    }

    /// Validates agreement between existence, bytes, and portable mode.
    pub fn validate(&self) -> Result<(), FacetError> {
        if self.bytes.is_some() != self.mode.is_some() {
            return Err(FacetError::InvalidImage);
        }
        if self.mode.is_some_and(|mode| mode & !0o777 != 0) {
            return Err(FacetError::InvalidMode);
        }
        Ok(())
    }

    /// Computes canonical image meaning.
    pub fn id(&self) -> Result<ImageId, FacetError> {
        self.validate()?;
        let (present, mode, bytes) = match (&self.bytes, self.mode) {
            (Some(bytes), Some(mode)) => {
                (true, number(u64::from(mode)), Datum::Bytes(bytes.clone()))
            }
            _ => (false, Datum::Nil, Datum::Nil),
        };
        FacetSemanticId::from_fields(vec![
            field("present", Datum::Bool(present))?,
            field("mode", mode)?,
            field("bytes", bytes)?,
        ])
    }
}

/// Exact region selection against one base revision.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RegionSelector {
    /// Whole artifact path.
    ExactPath(String),
    /// Inclusive start and exclusive end line within one path.
    LineRange {
        /// Repository-relative path.
        path: String,
        /// Zero-based inclusive line.
        start: u32,
        /// Zero-based exclusive line.
        end: u32,
    },
}

impl RegionSelector {
    pub(crate) fn id(&self) -> Result<RegionId, FacetError> {
        let (path, start, end) = match self {
            Self::ExactPath(path) => (path, Datum::Nil, Datum::Nil),
            Self::LineRange { path, start, end } if start < end => {
                (path, number(u64::from(*start)), number(u64::from(*end)))
            }
            Self::LineRange { .. } => return Err(FacetError::InvalidRegion),
        };
        validate_path(path)?;
        FacetSemanticId::from_fields(vec![
            field("path", Datum::String(path.clone()))?,
            field("start", start)?,
            field("end", end)?,
        ])
    }
}

/// Registered pure merge behavior.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum MergePolicy {
    /// Both-side changes always conflict.
    Exact,
    /// UTF-8 line merge under explicit work ceilings.
    Linewise {
        /// Maximum lines in each image.
        max_lines: u32,
        /// Maximum dynamic-programming cells per side.
        max_cells: u64,
    },
}

impl MergePolicy {
    pub(crate) fn id(&self) -> Result<MergePolicyId, FacetError> {
        let (kind, lines, cells) = match self {
            Self::Exact => ("exact", Datum::Nil, Datum::Nil),
            Self::Linewise {
                max_lines,
                max_cells,
            } if *max_lines > 0 && *max_cells > 0 => (
                "linewise",
                number(u64::from(*max_lines)),
                number(*max_cells),
            ),
            Self::Linewise { .. } => return Err(FacetError::InvalidMergePolicy),
        };
        FacetSemanticId::from_fields(vec![
            field("kind", Datum::String(kind.into()))?,
            field("max-lines", lines)?,
            field("max-cells", cells)?,
        ])
    }
}

/// Whether the region is authored directly or generated by another exact owner.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RegionOwnership {
    /// Directly authored by the facet owner.
    Authored,
    /// Generated and modifiable only through the generator owner.
    Generated {
        /// Sole generator owner.
        generator: OwnerId,
    },
}

/// Complete immutable pure facet specification.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ArtifactFacet {
    id: FacetId,
    /// Containing artifact.
    artifact: ArtifactId,
    /// Sole authoritative owner.
    owner: OwnerId,
    /// Exact selected region.
    region: RegionSelector,
    /// Semantic image projection.
    projection: ProjectionId,
    /// Registered pure merge policy.
    merge: MergePolicy,
    /// Externally supplied disclosure decision.
    disclosure: DisclosureDecisionId,
    /// Authored or generated ownership class.
    ownership: RegionOwnership,
}

impl ArtifactFacet {
    /// Validates and identifies a facet before any image is admitted.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        artifact: ArtifactId,
        owner: OwnerId,
        region: RegionSelector,
        projection: ProjectionId,
        merge: MergePolicy,
        disclosure: DisclosureDecisionId,
        ownership: RegionOwnership,
    ) -> Result<Self, FacetError> {
        if let RegionOwnership::Generated { generator } = &ownership
            && generator != &owner
        {
            return Err(FacetError::WrongOwner);
        }
        let region_id = region.id()?;
        let merge_id = merge.id()?;
        let ownership_value = match &ownership {
            RegionOwnership::Authored => Datum::String("authored".into()),
            RegionOwnership::Generated { generator } => generator.datum(),
        };
        let id = FacetSemanticId::from_fields(vec![
            field("artifact", artifact.datum())?,
            field("owner", owner.datum())?,
            field("region", region_id.datum())?,
            field("projection", projection.datum())?,
            field("merge", merge_id.datum())?,
            field("disclosure", disclosure.datum())?,
            field("ownership", ownership_value)?,
        ])?;
        Ok(Self {
            id,
            artifact,
            owner,
            region,
            projection,
            merge,
            disclosure,
            ownership,
        })
    }

    /// Returns the facet identity.
    pub const fn id(&self) -> &FacetId {
        &self.id
    }

    /// Returns the containing artifact.
    pub const fn artifact(&self) -> &ArtifactId {
        &self.artifact
    }

    /// Returns the sole authoritative owner.
    pub const fn owner(&self) -> &OwnerId {
        &self.owner
    }

    /// Returns the exact selected region.
    pub const fn region(&self) -> &RegionSelector {
        &self.region
    }

    /// Returns the semantic image projection.
    pub const fn projection(&self) -> &ProjectionId {
        &self.projection
    }

    /// Returns the registered pure merge policy.
    pub const fn merge_policy(&self) -> &MergePolicy {
        &self.merge
    }

    /// Returns the externally supplied disclosure decision.
    pub const fn disclosure(&self) -> &DisclosureDecisionId {
        &self.disclosure
    }

    /// Returns the authored or generated ownership class.
    pub const fn ownership(&self) -> &RegionOwnership {
        &self.ownership
    }
}

/// Marker implemented only by one image role.
pub trait ImageRole {
    /// Semantic id kind for this role.
    type Kind: crate::FacetIdKind;
}

/// Base role marker.
pub struct BaseRole;
impl ImageRole for BaseRole {
    type Kind = crate::BaseImageKind;
}
/// Observed role marker.
pub struct ObservedRole;
impl ImageRole for ObservedRole {
    type Kind = crate::ObservedImageKind;
}
/// Intended role marker.
pub struct IntendedRole;
impl ImageRole for IntendedRole {
    type Kind = crate::IntendedImageKind;
}

/// Image verified for one exact facet and one compile-time role.
pub struct RoleImage<R: ImageRole> {
    id: FacetSemanticId<R::Kind>,
    facet: FacetId,
    image: PortableImage,
    marker: PhantomData<fn() -> R>,
}

impl<R: ImageRole> Clone for RoleImage<R> {
    fn clone(&self) -> Self {
        Self {
            id: self.id.clone(),
            facet: self.facet.clone(),
            image: self.image.clone(),
            marker: PhantomData,
        }
    }
}
impl<R: ImageRole> std::fmt::Debug for RoleImage<R> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RoleImage")
            .field("id", &self.id)
            .field("facet", &self.facet)
            .field("image", &self.image)
            .finish()
    }
}
impl<R: ImageRole> PartialEq for RoleImage<R> {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id && self.facet == other.facet && self.image == other.image
    }
}
impl<R: ImageRole> Eq for RoleImage<R> {}

impl<R: ImageRole> RoleImage<R> {
    fn new(spec: &ArtifactFacet, image: PortableImage) -> Result<Self, FacetError> {
        image.validate()?;
        let image_id = image.id()?;
        let id = FacetSemanticId::from_fields(vec![
            field("facet", spec.id.datum())?,
            field("image", image_id.datum())?,
        ])?;
        Ok(Self {
            id,
            facet: spec.id.clone(),
            image,
            marker: PhantomData,
        })
    }

    /// Returns exact portable image content.
    pub const fn image(&self) -> &PortableImage {
        &self.image
    }

    pub(crate) fn facet(&self) -> &FacetId {
        &self.facet
    }
}

/// Checked base image. It cannot be passed as observed or intended.
pub type BaseImage = RoleImage<BaseRole>;
/// Checked observed image. It cannot be passed as base or intended.
pub type ObservedImage = RoleImage<ObservedRole>;
/// Checked intended image. It cannot be passed as base or observed.
pub type IntendedImage = RoleImage<IntendedRole>;

impl RoleImage<BaseRole> {
    /// Checks an image as the exact base role.
    pub fn check(spec: &ArtifactFacet, image: PortableImage) -> Result<Self, FacetError> {
        Self::new(spec, image)
    }
    /// Returns the base role identity.
    pub const fn id(&self) -> &BaseImageId {
        &self.id
    }
}
impl RoleImage<ObservedRole> {
    /// Checks an image as the exact observed role.
    pub fn check(spec: &ArtifactFacet, image: PortableImage) -> Result<Self, FacetError> {
        Self::new(spec, image)
    }
    /// Returns the observed role identity.
    pub const fn id(&self) -> &ObservedImageId {
        &self.id
    }
}
impl RoleImage<IntendedRole> {
    /// Checks an image as the exact intended role.
    pub fn check(spec: &ArtifactFacet, image: PortableImage) -> Result<Self, FacetError> {
        Self::new(spec, image)
    }
    /// Returns the intended role identity.
    pub const fn id(&self) -> &IntendedImageId {
        &self.id
    }
}

/// A postimage returned only by the checked pure merge law.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CheckedPostimage {
    id: PostimageId,
    image: PortableImage,
}

impl CheckedPostimage {
    pub(crate) fn new(spec: &ArtifactFacet, image: PortableImage) -> Result<Self, FacetError> {
        let image_id = image.id()?;
        let id = FacetSemanticId::from_fields(vec![
            field("facet", spec.id.datum())?,
            field("image", image_id.datum())?,
        ])?;
        Ok(Self { id, image })
    }

    /// Returns checked bytes and mode.
    pub const fn image(&self) -> &PortableImage {
        &self.image
    }

    /// Returns the postimage role identity.
    pub const fn id(&self) -> &PostimageId {
        &self.id
    }
}

fn validate_path(path: &str) -> Result<(), FacetError> {
    if path.is_empty()
        || path.len() > 4_096
        || path.starts_with('/')
        || path.contains('\\')
        || path
            .split('/')
            .any(|part| part.is_empty() || part == "." || part == "..")
    {
        Err(FacetError::InvalidRegion)
    } else {
        Ok(())
    }
}
